DealershipManager/Models/Dealership.cs
using System.Collections.Generic;
namespace DealershipManager.Models
{
  public class Dealership
  {
    public Dealership()
    {
      this.CarEntities = new HashSet<CarDealership>();
      this.SalesmanEntities = new HashSet<DealershipSalesman>();
    }
    public int DealershipId {get; set;}
    public string Name {get; set;}
    public virtual ICollection<CarDealership> CarEntities {get;set;}
    public virtual ICollection<DealershipSalesman> SalesmanEntities {get;set;}
  }
}

DealershipManager/Controllers/CarsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using DealershipManager.Models;
using System.Collections.Generic;
using System.Linq;

namespace DealershipManager.Controllers
{
  public class CarsController : Controller
  {
    private readonly DealershipManagerContext _db;

    public CarsController(DealershipManagerContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Cars.ToList());
    }

    public ActionResult Create()
    {
      SelectList dbData = new SelectList(_db.Dealerships, "DealershipId", "Name");
      //Create the select list item you want to add
      SelectListItem selListItem = new SelectListItem() { Value = "0", Text = "None" };
      //Create a list of select list items - this will be returned as your select list
      List<SelectListItem> newList = new List<SelectListItem>();
      //Add select list item to list of selectlistitems
      newList.Add(selListItem);
      newList.AddRange(dbData);
      //Return the list of selectlistitems as a selectlist
      ViewBag.DealershipId = new SelectList(newList, "Value", "Text", null);

      return View();
    }


    [HttpPost]
    public ActionResult Create(Car car, int DealershipId)
    {
      _db.Cars.Add(car);
      _db.SaveChanges();
      if (DealershipId != 0)
      {
        _db.CarDealership.Add(new CarDealership() { DealershipId = DealershipId, CarId = car.CarId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisCar = _db.Cars
          .Include(car => car.JoinEntities)
          .ThenInclude(join => join.Dealership)
          .FirstOrDefault(car => car.CarId == id);
      return View(thisCar);
    }

    public ActionResult Edit(int id)
    {
      var thisCar = _db.Cars.FirstOrDefault(car => car.CarId == id);
      return View(thisCar);
    }

    [HttpPost]
    public ActionResult Edit(Car car, int DealershipId, int PreviousDealershipId)
    {

      _db.Entry(car).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddDealership(int id)
    {
      var thisCar = _db.Cars.FirstOrDefault(car => car.CarId == id);
      ViewBag.DealershipId = new SelectList(_db.Dealerships, "DealershipId", "Name");
      return View(thisCar);
    }

    [HttpPost]
    public ActionResult AddDealership(Car car, int DealershipId)
    {
      if (DealershipId != 0)
      {
      _db.CarDealership.Add(new CarDealership() { DealershipId = DealershipId, CarId = car.CarId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisCar = _db.Cars.FirstOrDefault(car => car.CarId == id);
      return View(thisCar);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCar = _db.Cars.FirstOrDefault(car => car.CarId == id);
      _db.Cars.Remove(thisCar);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteDealership(int joinId)
    {
      var joinEntry = _db.CarDealership.FirstOrDefault(entry => entry.CarDealershipId == joinId);
      _db.CarDealership.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

DealershipManager/Controllers/DealershipsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using DealershipManager.Models;
using System.Collections.Generic;
using System.Linq;

namespace DealershipManager.Controllers
{
  public class DealershipsController : Controller
  {
    private readonly DealershipManagerContext _db;

    public DealershipsController(DealershipManagerContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Dealership> model = _db.Dealerships.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Dealership dealership)
    {
      _db.Dealerships.Add(dealership);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisDealership = _db.Dealerships
          .Include(dealership => dealership.CarEntities)
          .ThenInclude(join => join.Car)
          .Include(dealership => dealership.SalesmanEntities)
          .ThenInclude(join => join.Salesman)
          .FirstOrDefault(dealership => dealership.DealershipId == id);
      return View(thisDealership);
    }
    public ActionResult Edit(int id)
    {
      var thisDealership = _db.Dealerships.FirstOrDefault(dealership => dealership.DealershipId == id);
      return View(thisDealership);
    }

    [HttpPost]
    public ActionResult Edit(Dealership dealership)
    {
      _db.Entry(dealership).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisDealership = _db.Dealerships.FirstOrDefault(dealership => dealership.DealershipId == id);
      return View(thisDealership);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisDealership = _db.Dealerships.FirstOrDefault(dealership => dealership.DealershipId == id);
      _db.Dealerships.Remove(thisDealership);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

DealershipManager/Controllers/SalesmenController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using DealershipManager.Models;
using System.Collections.Generic;
using System.Linq;

namespace DealershipManager.Controllers
{
  public class SalesmenController : Controller
  {
    private readonly DealershipManagerContext _db;

    public SalesmenController(DealershipManagerContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Salesmen.ToList());
    }

    public ActionResult Create()
    {
      SelectList dbData = new SelectList(_db.Dealerships, "DealershipId", "Name");
      //Create the select list item you want to add
      SelectListItem selListItem = new SelectListItem() { Value = "0", Text = "None" };
      //Create a list of select list items - this will be returned as your select list
      List<SelectListItem> newList = new List<SelectListItem>();
      //Add select list item to list of selectlistitems
      newList.Add(selListItem);
      newList.AddRange(dbData);
      //Return the list of selectlistitems as a selectlist
      ViewBag.DealershipId = new SelectList(newList, "Value", "Text", null);
      return View();
    }

    [HttpPost]
    public ActionResult Create(Salesman salesman, int DealershipId)
    {
      _db.Salesmen.Add(salesman);
      _db.SaveChanges();
      if (DealershipId != 0)
      {
        _db.DealershipSalesman.Add(new DealershipSalesman() { DealershipId = DealershipId, SalesmanId = salesman.SalesmanId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisSalesman = _db.Salesmen
          .Include(salesman => salesman.JoinEntities)
          .ThenInclude(join => join.Dealership)
          .FirstOrDefault(salesman => salesman.SalesmanId == id);
      return View(thisSalesman);
    }

    public ActionResult Edit(int id)
    {
      var thisSalesman = _db.Salesmen.FirstOrDefault(salesman => salesman.SalesmanId == id);
      return View(thisSalesman);
    }

    [HttpPost]
    public ActionResult Edit(Salesman salesman, int DealershipId)
    {
      if (DealershipId != 0)
      {
        _db.DealershipSalesman.Add(new DealershipSalesman() { DealershipId = DealershipId, SalesmanId = salesman.SalesmanId });
      }
      _db.Entry(salesman).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddDealership(int id)
    {
      var thisSalesman = _db.Salesmen.FirstOrDefault(salesman => salesman.SalesmanId == id);
      ViewBag.DealershipId = new SelectList(_db.Dealerships, "DealershipId", "Name");
      return View(thisSalesman);
    }

    [HttpPost]
    public ActionResult AddDealership(Salesman salesman, int DealershipId)
    {
      if (DealershipId != 0)
      {
      _db.DealershipSalesman.Add(new DealershipSalesman() { DealershipId = DealershipId, SalesmanId = salesman.SalesmanId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisSalesman = _db.Salesmen.FirstOrDefault(salesman => salesman.SalesmanId == id);
      return View(thisSalesman);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisSalesman = _db.Salesmen.FirstOrDefault(salesman => salesman.SalesmanId == id);
      _db.Salesmen.Remove(thisSalesman);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteDealership(int joinId)
    {
      var joinEntry = _db.DealershipSalesman.FirstOrDefault(entry => entry.DealershipSalesmanId == joinId);
      _db.DealershipSalesman.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

DealershipManager/Views/Dealerships/Create.cshtml
@{
  Layout = "_Layout";
}

@model DealershipManager.Models.Dealership

<h1>Add a new dealership: </h1>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name,
  new {required="required"})
  <input type="submit" value="Add new dealership" class="btn btn-lg btn-dark"/>
}

<p>@Html.ActionLink("return to dealerships page", "Index")</p>
<p>@Html.ActionLink("Return to homepage", "Index", "Home")</p>

DealershipManager/Views/Dealerships/Delete.cshtml
@{
  Layout = "_Layout";
}

@model DealershipManager.Models.Dealership

<h2>Are you sure you want to delete this dealership?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-lg btn-dark"/>
}
<p>@Html.ActionLink("return to dealerships page", "Index")</p>

DealershipManager/Views/Dealerships/Details.cshtml
@{
  Layout = "_Layout";
}

@model DealershipManager.Models.Dealership
@using DealershipManager.Models

<h2>Dealership Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model=> model.Name): @Html.DisplayFor(model => model.Name)</h3>

<h3>Cars: </h3>
@if(@Model.CarEntities.Count == 0)
{
  <p>This dealership does not contain any cars.</p>
}

@foreach(CarDealership join in Model.CarEntities)
{
  <li>@Html.ActionLink($"{join.Car.Year}" + " " + $"{join.Car.Make}" + " / " + $"{join.Car.Model}", "Details", "Cars", new { id = join.Car.CarId})</li>
}

<h3>Salespeople: </h3>
@if(@Model.SalesmanEntities.Count == 0)
{
  <p>This dealership does not contain any salesmen.</p>
}

@foreach(DealershipSalesman join in Model.SalesmanEntities)
{
  <li>@Html.ActionLink($"{join.Salesman.Name}", "Details", "Salesmen", new { id = join.Salesman.SalesmanId})</li>
}

<p>@Html.ActionLink("Edit Dealership", "Edit", new { id = Model.DealershipId })</p>
<p>@Html.ActionLink("Delete Dealership", "Delete", new {id = Model.DealershipId})</p>
<p>@Html.ActionLink("Back to dealerships", "Index")</p>
<p>@Html.ActionLink("Return to homepage", "Index", "Home")</p>

DealershipManager/Views/Dealerships/Edit.cshtml
@{
  Layout = "_Layout";
}

@model DealershipManager.Models.Dealership

<h2>Edit Dealership</h2>

<h4>Edit this dealership: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.DealershipId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  <input type="submit" value="Save" class="btn btn-lg btn-dark"/>
}
<p>@Html.ActionLink("Delete Dealership", "Delete", new {id = Model.DealershipId})</p>
<p>@Html.ActionLink("Back to Dealership List", "index")</p>

DealershipManager/Views/Dealerships/Index.cshtml
@{
  Layout = "_Layout";
}

@using DealershipManager.Models
@model List<DealershipManager.Models.Dealership>

<h1>All Dealerships:</h1>

@if(@Model.Count == 0)
{
  <h3>No dealerships have been added yet.</h3>
}

@foreach(Dealership dealership in Model)
{
  <li>@Html.ActionLink($"{dealership.Name}", "Details", new { id = dealership.DealershipId})</li>
}

<p>@Html.ActionLink("Add a new dealership", "Create")</p>
<p>@Html.ActionLink("Return to homepage", "Index", "Home")</p>